# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160313_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
