# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_signup_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phone_number',
            field=models.CharField(max_length=120),
        ),
    ]
